# Generated by Django 6.1 on 2026-08-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=150)),
                ('anio_estreno', models.IntegerField()),
                ('estado', models.CharField(choices=[('vista', 'Vista'), ('progreso', 'En progreso'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
            ],
        ),
    ]
