# Generated by Django 6.1 on 2026-08-27 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-anio_estreno', '-fecha_agregada'], 'verbose_name': 'película', 'verbose_name_plural': 'películas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_agregada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('scifi', 'Ciencia ficción'), ('romance', 'Romance'), ('documental', 'Documental'), ('animacion', 'Animación'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuacion',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
