# Generated by Django 6.1 on 2026-08-27 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_pelicula_options_alter_perfil_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='usuario',
        ),
        migrations.CreateModel(
            name='EstadoPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('vista', 'Vista'), ('progreso', 'En progreso'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_usuarios', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_peliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estado de película',
                'verbose_name_plural': 'estados de películas',
                'ordering': ['-actualizado'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
    ]
