# Generated by Django 6.1 on 2026-09-28 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_remove_pelicula_estado_remove_pelicula_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='calificacion_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='total_calificaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calificación',
                'verbose_name_plural': 'calificaciones',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'pelicula')},
            },
        ),
    ]
