# Generated by Django 6.1 on 2026-09-29 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_pelicula_calificacion_promedio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=100)),
                ('biografia', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=100)),
                ('biografia', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(default=0, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='visualizaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(blank=True, related_name='peliculas', to='peliculas.actor'),
        ),
        migrations.CreateModel(
            name='HistorialVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion_vista', models.PositiveIntegerField(default=0, help_text='Segundos vistos')),
                ('progreso', models.PositiveIntegerField(default=0, help_text='Porcentaje de avance')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_visualizacion', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_visualizacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de visualización',
                'verbose_name_plural': 'historiales de visualización',
                'ordering': ['-fecha_visualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ListaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('es_privada', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('peliculas', models.ManyToManyField(blank=True, related_name='en_listas_personalizadas', to='peliculas.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_personalizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lista personalizada',
                'verbose_name_plural': 'listas personalizadas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
