# Generated by Django 6.1 on 2026-09-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_completar_catalogo_por_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='video_fondo_url',
            field=models.URLField(blank=True, help_text='URL opcional de un video MP4 para el banner principal.'),
        ),
    ]
