# Generated by Django 6.1 on 2026-09-29 19:00

from django.db import migrations, models


def seleccionar_portadas_iniciales(apps, schema_editor):
    Pelicula = apps.get_model('peliculas', 'Pelicula')
    base = schema_editor.connection.alias
    ids = list(
        Pelicula.objects.using(base)
        .exclude(portada='')
        .exclude(portada__isnull=True)
        .order_by('-calificacion_promedio', '-visualizaciones', 'titulo')
        .values_list('pk', flat=True)[:5]
    )
    Pelicula.objects.using(base).filter(pk__in=ids).update(mostrar_en_banner=True)


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0008_pelicula_video_fondo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='mostrar_en_banner',
            field=models.BooleanField(default=False, help_text='Incluye esta película en el banner del catálogo.'),
        ),
        migrations.RunPython(seleccionar_portadas_iniciales, migrations.RunPython.noop),
    ]
